config/routes.rb
History::Application.routes.draw do
  resources :chancellors

end

app/models/chancellor.rb
class Chancellor < ActiveRecord::Base
  attr_accessible :birthday, :day_of_death, :first_name, :inauguration, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chancellors_controller.rb
class ChancellorsController < ApplicationController
  # GET /chancellors
  # GET /chancellors.json
  def index
    @chancellors = Chancellor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chancellors }
    end
  end

  # GET /chancellors/1
  # GET /chancellors/1.json
  def show
    @chancellor = Chancellor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chancellor }
    end
  end

  # GET /chancellors/new
  # GET /chancellors/new.json
  def new
    @chancellor = Chancellor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @chancellor }
    end
  end

  # GET /chancellors/1/edit
  def edit
    @chancellor = Chancellor.find(params[:id])
  end

  # POST /chancellors
  # POST /chancellors.json
  def create
    @chancellor = Chancellor.new(params[:chancellor])

    respond_to do |format|
      if @chancellor.save
        format.html { redirect_to @chancellor, notice: 'Chancellor was successfully created.' }
        format.json { render json: @chancellor, status: :created, location: @chancellor }
      else
        format.html { render action: "new" }
        format.json { render json: @chancellor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /chancellors/1
  # PUT /chancellors/1.json
  def update
    @chancellor = Chancellor.find(params[:id])

    respond_to do |format|
      if @chancellor.update_attributes(params[:chancellor])
        format.html { redirect_to @chancellor, notice: 'Chancellor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @chancellor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chancellors/1
  # DELETE /chancellors/1.json
  def destroy
    @chancellor = Chancellor.find(params[:id])
    @chancellor.destroy

    respond_to do |format|
      format.html { redirect_to chancellors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chancellors_helper.rb
module ChancellorsHelper
end

app/views/chancellors/_form.html.erb
<%= form_for(@chancellor) do |f| %>
  <% if @chancellor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chancellor.errors.count, "error") %> prohibited this chancellor from being saved:</h2>

      <ul>
      <% @chancellor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :day_of_death %><br />
    <%= f.date_select :day_of_death %>
  </div>
  <div class="field">
    <%= f.label :inauguration %><br />
    <%= f.date_select :inauguration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chancellors/edit.html.erb
<h1>Editing chancellor</h1>

<%= render 'form' %>

<%= link_to 'Show', @chancellor %> |
<%= link_to 'Back', chancellors_path %>

app/views/chancellors/index.html.erb
<h1>Listing chancellors</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Birthday</th>
    <th>Day of death</th>
    <th>Inauguration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chancellors.each do |chancellor| %>
  <tr>
    <td><%= chancellor.first_name %></td>
    <td><%= chancellor.last_name %></td>
    <td><%= chancellor.birthday %></td>
    <td><%= chancellor.day_of_death %></td>
    <td><%= chancellor.inauguration %></td>
    <td><%= link_to 'Show', chancellor %></td>
    <td><%= link_to 'Edit', edit_chancellor_path(chancellor) %></td>
    <td><%= link_to 'Destroy', chancellor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chancellor', new_chancellor_path %>

app/views/chancellors/new.html.erb
<h1>New chancellor</h1>

<%= render 'form' %>

<%= link_to 'Back', chancellors_path %>

app/views/chancellors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @chancellor.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @chancellor.last_name %>
</p>

<p>
  <b>Birthday:</b>
  <%= @chancellor.birthday %>
</p>

<p>
  <b>Day of death:</b>
  <%= @chancellor.day_of_death %>
</p>

<p>
  <b>Inauguration:</b>
  <%= @chancellor.inauguration %>
</p>


<%= link_to 'Edit', edit_chancellor_path(@chancellor) %> |
<%= link_to 'Back', chancellors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>History</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>